version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "ci/cd"
    commit-message:
      prefix: "ci"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/backstage-local-test"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "backstage"
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "platform-modules"
    commit-message:
      prefix: "deps"
      include: "scope"
