skip-check:
  - CKV_AWS_103
  - CKV_AWS_109
  - CKV_AWS_111
  - CKV_AWS_118
  - CKV_AWS_144
  - CKV_AWS_152
  - CKV_AWS_2
  - CKV_AWS_224
  - CKV_AWS_231
  - CKV_AWS_232
  - CKV_AWS_24
  - CKV_AWS_260
  - CKV_AWS_338
  - CKV_AWS_356
  - CKV_AWS_378
  - CKV_AWS_38
  - CKV_AWS_382
  - CKV_AWS_39
  - CKV_AWS_58
  - CKV_AWS_88
  - CKV_TF_1
  - CKV2_AWS_1
  - CKV2_AWS_20
  - CKV2_AWS_30
  - CKV2_AWS_31
  - CKV2_AWS_38
  - CKV2_AWS_39
  - CKV2_AWS_41
  - CKV2_AWS_5
  - CKV2_AWS_62
  - CKV2_AWS_69
  - CKV2_AWS_76
