bucket_name              = "jenkins-tfstate-platform"
aws_region               = "eu-north-1"
aws_account_id           = "111111111111"
environment              = "dev"
instance_type            = "t3.small"
vpc_cidr                 = "10.10.0.0/16"
vpc_name                 = "jenkins-dev-vpc"
cidr_public_subnet       = ["10.10.1.0/24", "10.10.2.0/24"]
cidr_private_subnet      = ["10.10.11.0/24", "10.10.12.0/24"]
eu_availability_zone     = ["eu-north-1a", "eu-north-1b"]
public_key               = "ssh-rsa REPLACE_ME_DEV"
run_ansible              = false
enable_observability     = false
enable_grafana_service   = false
enable_vault_integration = false
vault_address            = ""
vault_token              = ""
vault_namespace          = ""
vault_skip_tls_verify    = false
vault_kv_mount           = "secret"
vault_secret_path        = "jenkins/platform/test"
vault_secret_key         = "value"
tags = {
  Owner      = "platform-team"
  CostCenter = "engineering-dev"
  Purpose    = "jenkins-development"
}
