apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jenkins-infrastructure
  description: Core Jenkins infrastructure stack
  tags:
    - terraform
    - aws
    - jenkins
spec:
  type: terraform-module
  lifecycle: production
  owner: platform-team
  system: internal-developer-platform
  dependsOn:
    - resource:default/jenkins-ec2-runtime
    - resource:default/aws-vpc-network
