---
- name: Configure Jenkins Server
  hosts: tag_Name__Jenkins_Ubuntu_Linux_EC2
  become: true
  tasks:
    # Update apt cache
    - name: Update apt cache
      apt:
        update_cache: yes

    # Check if Jenkins is already installed
    - name: Check if Jenkins is installed
      shell: dpkg -l | grep jenkins
      register: jenkins_installed
      ignore_errors: true

    # Add Jenkins repository key only if Jenkins is not installed
    - name: Add Jenkins repository key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present
      when: jenkins_installed.rc != 0

    # Add Jenkins repository only if Jenkins is not installed
    - name: Add Jenkins repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        state: present
      when: jenkins_installed.rc != 0

    # Install Jenkins only if it is not installed
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
      when: jenkins_installed.rc != 0

    # Ensure Jenkins service is running
    - name: Ensure Jenkins service is running
      service:
        name: jenkins
        state: started
        enabled: true

    # Install Docker
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    # Add Jenkins user to Docker group
    - name: Add Jenkins user to Docker group
      user:
        name: jenkins
        groups: docker
        append: true

    # Install Git
    - name: Install Git
      apt:
        name: git
        state: present

